#!groovy

pipeline {

  agent any

  parameters {
    string(
      name: 'AD_HOC_COMMAND',
      defaultValue: '',
      description: 'Ansible ad-hoc command'
    )
    credentials(
      name: 'INVENTORY',
      defaultValue: '',
      description: '',
    )
    string(
      name: 'WORKING_DIR',
      defaultValue: '/tmp/ad-hoc',
      description: 'Job working directory'
    )
  }

  stages {
    stage('Create ansible.cfg file') {
      steps {
        sh "rm -rf ${params.WORKING_DIR}"
        sh "mkdir -p ${params.WORKING_DIR}"
        dir ("${params.WORKING_DIR}") {
          sh "echo '[defaults]' > ansible.cfg"
          sh "echo 'host_key_checking = False' >> ansible.cfg"
        }
      }
    }

    stage('Configure ansible inventory file') {
      steps {
        dir ("${params.WORKING_DIR}") {
          wrap([$class: 'MaskPasswordsBuildWrapper']) {
            sh "cat ${params.INVENTORY} > inventory"
          }
        }
      }
    }

    stage('excute ansible-playbook command') {
      steps {
        dir ("${params.WORKING_DIR}") {
          sh "ansible all \
              -i inventory \
              ${params.AD_HOC_COMMAND} \
              | tee ansible.log"
        }
      }
    }

    stage('Analyze Ansible log and output result') {
      steps {
        dir ("${params.WORKING_DIR}") {
          script {
            def output = sh(
                            returnStdout: true,
                            script: "head ansible.log"
                         )

            if (output.contains("SUCCESS")) {
              sh "echo success"
            } else {
              error "ansible-playbook error\n$output"
            }
          }
        }
      }
    }
  }
}
