#!groovy

pipeline {

  agent any

  environment {
    DATAHOST = credentials('app_ip_address')

    DATAHOST_PORT = credentials('ansible_port')

    DATAHOST_DATA_PATH = "/home/ansible/redmine-backup"

    LOCALHOST_DATA_PATH = "/home/ansible/redmine-backup"
  }

  stages {
    stage('Retrive Wordpress backup data from wordpress running site') {
      steps {
        sh "sudo -u ansible rm -rf ${env.LOCALHOST_DATA_PATH}"
        sh "sudo -u ansible mkdir -p ${env.LOCALHOST_DATA_PATH}"
        sh "sudo -u ansible scp -P ${env.DATAHOST_PORT} ansible@${env.DATAHOST}:${env.DATAHOST_DATA_PATH}/redmine.psql ${env.LOCALHOST_DATA_PATH}/"
        sh "sudo -u ansible scp -P ${env.DATAHOST_PORT} ansible@${env.DATAHOST}:${env.DATAHOST_DATA_PATH}/files.tar.gz ${env.LOCALHOST_DATA_PATH}/"
        sh "sudo -u ansible scp -P ${env.DATAHOST_PORT} ansible@${env.DATAHOST}:${env.DATAHOST_DATA_PATH}/git.tar.gz ${env.LOCALHOST_DATA_PATH}/"
      }
    }
  }
}
