#!groovy

pipeline {

  agent any

  environment {
    ANSIBLE_PLAYBOOK = 'site'

    GIT_URL_ANSIBLE = 'https://github.com/TomonoriMatsumura/ansible_centos7_jenkins_install.git'

    INVENTORY = credentials('node1_ansible_inventory')

    WORKING_DIR = "node1_${env.ANSIBLE_PLAYBOOK}"
  }

  parameters {
    string(
      name: 'GIT_BRANCHES_ANSIBLE',
      defaultValue: '*/master',
      description: "Git branch or tag name or commit id to retrieve"
    )
  }

  stages {
    stage('Excute ansible-playbook command') {
      steps {
        build job: 'ansible/playbook',
          parameters: [
                        string(
                          name: 'ANSIBLE_PLAYBOOK',
                          value: "${env.ANSIBLE_PLAYBOOK}"
                        ),
                        credentials(
                          name: 'INVENTORY',
                          value: "${env.INVENTORY}"
                        ),
                        string(
                          name: 'GIT_BRANCHES_ANSIBLE',
                          value: "${params.GIT_BRANCHES_ANSIBLE}"
                        ),
                        string(
                          name: 'GIT_URL',
                          value: "${env.GIT_URL_ANSIBLE}"
                        ),
                        string(
                          name: 'WORKING_DIR',
                          value: "${env.WORKING_DIR}"
                        )
                      ]
      }
    }
  }
}
