#!groovy

pipeline {

  agent any

  environment {
    ANSIBLE_PLAYBOOK = 'wordpress_create-backup'

    INVENTORY = credentials('app_ansible_inventory')

    EXTRA_ARGS = "-e 'backup_data_path=/home/wordpress/wp-backup_solution-log' \
                  -e 'backup_data_group=wordpress' \
                  -e 'backup_data_owner=wordpress' \
                  -e 'db_dump_data_sql=solution_log.sql' \
                  -e 'wp_installed_path=/var/www/html/wordpress/solution-log'"

    WORKING_DIR = "/home/ansible/.jenkins/app_${env.ANSIBLE_PLAYBOOK}"
  }

  stages {
    stage('excute ansible-playbook command') {
      steps {
        build job: 'ansible/common/excute/playbook',
          parameters: [
                        string(
                          name: 'ANSIBLE_PLAYBOOK',
                          value: "${env.ANSIBLE_PLAYBOOK}"
                        ),
                        credentials(
                          name: 'INVENTORY',
                          value: "${env.INVENTORY}"
                        ),
                        string(
                          name: 'WORKING_DIR',
                          value: "${env.WORKING_DIR}"
                        ),
                        string(
                          name: 'EXTRA_ARGS',
                          value: "${env.EXTRA_ARGS}"
                        )
                      ]
      }
    }
  }
}
