#!groovy

pipeline {

  agent any

  parameters {
    string(
      name: 'WORKING_DIR',
      defaultValue: '/tmp/git-repo',
      description: 'Job working directory'
    )
    credentials(
      name: 'INVENTORY',
      defaultValue: '',
      description: '',
    )
  }

  stages {
    stage('set ansible inventory file') {
      steps {
          sh "rm -rf /tmp${params.WORKING_DIR}"
          sh "mkdir -p /tmp${params.WORKING_DIR}/inventories"
          sh "touch /tmp${params.WORKING_DIR}/inventories/host"
          sh "cat ${params.INVENTORY} > /tmp${params.WORKING_DIR}/inventories/host"
      }
    }
  }
}
