#!groovy

pipeline {

  agent any

  parameters {
    string(
      name: 'WORKING_DIR',
      defaultValue: '/tmp/git-repo',
      description: 'Job working directory'
    )
    credentials(
      name: 'ANSIBLE_HOST',
      defaultValue: '127.0.0.1',
      description: 'Vaule of ansible_host',
    )
    password(
      name: 'ANSIBLE_HOST_PASSWORD',
      defaultValue: 'password',
      description: 'Value of ansible_host_password'
    )
  }

  stages {
    stage('set ansible inventory file') {
      steps {
        wrap([$class: 'MaskPasswordsBuildWrapper']) {
          sh "sudo -u ansible sed -i -e \"s/ansible_become_pass: password/ansible_become_pass: ${params.ANSIBLE_HOST_PASSWORD}/g\" ${params.WORKING_DIR}/inventories/host"

          sh "sudo -u ansible sed -i -e \"s/my server:/${params.ANSIBLE_HOST}:/g\" ${params.WORKING_DIR}/inventories/host"

          sh "sudo -u ansible sed -i -e \"s/ansible_host: example.com/ansible_host: ${params.ANSIBLE_HOST}/g\" ${params.WORKING_DIR}/inventories/host"

          sh "sudo -u ansible sed -i -e \"s/ansible_port: 22/ansible_port: ${env.ANSIBLE_PORT}/g\" ${params.WORKING_DIR}/inventories/host"

          sh "sudo -u ansible sed -i -e \"s/ansible_user: root/ansible_user: ansible/g\" ${params.WORKING_DIR}/inventories/host"
        }
      }
    }
  }
}
