#!groovy

pipeline {

  agent any

  parameters {
    string(
      name: 'VAULT_PASSWORD_FILE',
      defaultValue: '/tmp/password.txt',
      description: 'Ansible vault password file path'
    )
    password(
      name: 'VAULT_PASS',
      defaultValue: 'password',
      description: 'Ansible vault password: unhashed strings'
    )
  }

  stages {
    stage('Create Ansible vault password file') {
      steps {
        wrap([$class: 'MaskPasswordsBuildWrapper']) {
          sh "sudo -u ansible rm -rf ${params.VAULT_PASSWORD_FILE}"
          sh "sudo -u ansible touch ${params.VAULT_PASSWORD_FILE}"
          sh "sudo -u ansible chmod 777 ${params.VAULT_PASSWORD_FILE}"
          sh "sudo -u ansible echo ${params.VAULT_PASS} > ${params.VAULT_PASSWORD_FILE}"
          sh "sudo -u ansible chmod 600 ${params.VAULT_PASSWORD_FILE}"
        }
      }
    }
  }
}
