#!groovy

pipeline {

  agent any

  environment {
    ANSIBLE_PLAYBOOK = 'wordpress_install'

    EXTRA_ARGS = "--tags 'language_php_install'"

    INVENTORY = credentials('node1_ansible_inventory')

    WORKING_DIR = "node1_languate_php_install"
  }

  parameters {
    string(
      name: 'GIT_BRANCHES_ANSIBLE',
      defaultValue: '*/master',
      description: "Git branch or tag name or commit id to retrieve of ${env.ANSIBLE_GITHUB_URL}"
    )
    string(
      name: 'REMI_REPO_ID',
      defaultValue: 'remi-php72',
      description: 'Remi\'s RPM Repository ID to install php / example: remi-php71,remi-php72,... PHP version need to be greater than 7.0'
    )
  }

  stages {
    stage('excute ansible-playbook command') {
      steps {
        build job: 'ansible/common/excute/playbook',
          parameters: [
                        string(
                          name: 'ANSIBLE_PLAYBOOK',
                          value: "${env.ANSIBLE_PLAYBOOK}"
                        ),
                        string(
                          name: 'EXTRA_ARGS',
                          value: "${env.EXTRA_ARGS} -e 'remi_repo=${params.REMI_REPO_ID}'"
                        ),
                        credentials(
                          name: 'INVENTORY',
                          value: "${env.INVENTORY}"
                        ),
                        string(
                          name: 'GIT_BRANCHES_ANSIBLE',
                          value: "${params.GIT_BRANCHES_ANSIBLE}"
                        ),
                        string(
                          name: 'WORKING_DIR',
                          value: "${env.WORKING_DIR}"
                        )
                      ]
      }
    }
  }
}
