#!groovy

pipeline {

  agent any

  parameters {
    string(
      name: 'WORKING_DIR',
      defaultValue: '/tmp/git-repo',
      description: 'Job working directory'
    )
  }

  stages {
    stage('Get ansible-playbook result from ansible log file') {
      steps {
        script {
          def output = sh(
                          returnStdout: true,
                          script: "sudo -u ansible tail -n 2 ${env.WORKING_DIR}/.ansible.log"
                       )
          if (output.contains("unreachable=1")) {
            error 'failed'
          } else {
            sh "echo success"
          }
        }
      }
    }
  }
}
