#!groovy

pipeline {

  agent any

  parameters {
    string(
      name: 'WORKING_DIR',
      defaultValue: '/tmp/git-repo',
      description: 'Job working directory'
    )
  }

  stages {
    stage('Initialize working wirectory') {
      steps {
        sh "sudo -u ansible rm -rf ${params.WORKING_DIR}"
      }
    }
    stage('Git clone') {
      steps {
        sh "sudo -u ansible mkdir ${params.WORKING_DIR}"
        sh "sudo -u ansible git clone https://github.com/TomonoriMatsumura/ansible.git -b topic ${params.WORKING_DIR}"
      }
    }
  }
}
