#!groovy

pipeline {

  agent any

  environment {
    ANSIBLE_PLAYBOOK = 'owncloud_install'

    INVENTORY = credentials('node1_ansible_inventory')

    REQUIRE_HOST_1 = credentials('require_host_1')

    REQUIRE_HOST_2 = credentials('require_host_2')

    EXTRA_ARGS = "--skip-tags 'httpd_install,language_php_71_install,rdb_mariadb_install' \
                  -e 'db_name=mydrive1' \
                  -e 'db_user=my' \
                  -e 'db_password=ocmydrive1' \
                  -e 'oc_install_dir=/var/www/html/mydrive' \
                  -e 'httpd_conf_confd=oc_mydrive.conf' \
                  -e '{ \"requires\": [ { \"${env.REQUIRE_HOST_1}\": \"Require host ${env.REQUIRE_HOST_1}\" }, { \"${env.REQUIRE_HOST_2}\": \"Require host ${env.REQUIRE_HOST_2}\" } ] }'"
    WORKING_DIR = "/home/ansible/.jenkins/node1_${env.ANSIBLE_PLAYBOOK}"
  }

  stages {
    stage('excute ansible-playbook command') {
      steps {
        build job: 'ansible/common/excute/playbook',
          parameters: [
                        string(
                          name: 'ANSIBLE_PLAYBOOK',
                          value: "${env.ANSIBLE_PLAYBOOK}"
                        ),
                        credentials(
                          name: 'INVENTORY',
                          value: "${env.INVENTORY}"
                        ),
                        string(
                          name: 'WORKING_DIR',
                          value: "${env.WORKING_DIR}"
                        ),
                        string(
                          name: 'EXTRA_ARGS',
                          value: "${env.EXTRA_ARGS}"
                        )
                      ]
      }
    }
  }
}
