#!groovy

pipeline {

  agent any

  environment {
    ANSIBLE_PLAYBOOK = 'redmine_create-backup'

    INVENTORY = credentials('app_ansible_inventory')

    REDMINE_DB_PASS = credentials('redmine_db_password')

    EXTRA_ARGS = "-e 'db_password=${env.REDMINE_DB_PASS}' \
                  -e 'backup_data_path=/home/rmbackup/data' \
                  -e 'backup_data_group=wpbackup' \
                  -e 'backup_data_owner=wpbackup'"

    WORKING_DIR = "/home/ansible/.jenkins/app_${env.ANSIBLE_PLAYBOOK}"
  }

  stages {
    stage('excute ansible-playbook command') {
      steps {
        build job: 'ansible/common/excute/playbook',
          parameters: [
                        string(
                          name: 'ANSIBLE_PLAYBOOK',
                          value: "${env.ANSIBLE_PLAYBOOK}"
                        ),
                        credentials(
                          name: 'INVENTORY',
                          value: "${env.INVENTORY}"
                        ),
                        string(
                          name: 'WORKING_DIR',
                          value: "${env.WORKING_DIR}"
                        ),
                        string(
                          name: 'EXTRA_ARGS',
                          value: "${env.EXTRA_ARGS}"
                        )
                      ]
      }
    }
  }
}
