#!groovy

pipeline {

  agent any

  environment {
    ANSIBLE_PLAYBOOK = 'redmine_create-backup'

    INVENTORY = credentials('app_ansible_inventory')

    REDMINE_DB_PASS = credentials('redmine_db_password')

    EXTRA_ARGS = "-e 'db_password=${env.REDMINE_DB_PASS}' \
                  -e 'backup_data_path=/home/ansible/redmine-backup' \
                  -e 'backup_data_group=ansible' \
                  -e 'backup_data_owner=ansible'"

    WORKING_DIR = "app_${env.ANSIBLE_PLAYBOOK}"
  }

  parameters {
    string(
      name: 'GIT_BRANCHES_ANSIBLE',
      defaultValue: '*/master',
      description: "Git branch or tag name or commit id to retrieve of ${env.ANSIBLE_GITHUB_URL}"
    )
  }

  stages {
    stage('excute ansible-playbook command') {
      steps {
        build job: 'ansible/common/excute/playbook',
          parameters: [
                        string(
                          name: 'ANSIBLE_PLAYBOOK',
                          value: "${env.ANSIBLE_PLAYBOOK}"
                        ),
                        credentials(
                          name: 'INVENTORY',
                          value: "${env.INVENTORY}"
                        ),
                        string(
                          name: 'GIT_BRANCHES_ANSIBLE',
                          value: "${params.GIT_BRANCHES_ANSIBLE}"
                        ),
                        string(
                          name: 'WORKING_DIR',
                          value: "${env.WORKING_DIR}"
                        ),
                        string(
                          name: 'EXTRA_ARGS',
                          value: "${env.EXTRA_ARGS}"
                        )
                      ]
      }
    }
  }
}
