#!groovy

pipeline {

  agent any

  environment {
    home = "/home/ansible"

    DATAHOST = credentials('app_ip_address')

    DATAHOST_PORT = credentials('ansible_port')

    DATAHOST_DATA_PATH = "${env.home}/redmine-backup"

    LOCALHOST_DATA_PATH = "${env.home}/redmine-backup"
  }

  stages {
    stage('Retrive Redmine backup data from Redmine running site') {
      steps {
        sh "rm -rf ${env.LOCALHOST_DATA_PATH}"

        sh "mkdir -p ${env.LOCALHOST_DATA_PATH}"

        sh "scp -P ${env.DATAHOST_PORT} -r ansible@${env.DATAHOST}:${env.DATAHOST_DATA_PATH} ${env.home}"
      }
    }
  }
}
