#!groovy

pipeline {

  agent any

  environment {
    GIT_HOST = credentials('app_ip_address')

    SSH_PORT = credentials('ansible_port')

    GIT_REPO = "ssh://jenkinsbackup@${env.GIT_HOST}:${env.SSH_PORT}/home/jenkinsbackup/git/backup"

    WORKING_DIR = "jenkins_get-backup"
  }

  parameters {
    string(
      name: 'GIT_RETRIEVE_BRANCHS',
      defaultValue: 'master',
      description: 'Git branch or tag to retrieve'
    )
  }

  stages {
    stage('Retrive source code from Git Server') {
      steps {
        checkout(
          [
            $class: 'GitSCM',
            branches: [
              [
                name: "*/${params.GIT_RETRIEVE_BRANCHS}"
              ]
            ],
            extensions: [
              [
                $class: 'RelativeTargetDirectory',
                relativeTargetDir: "${env.WORKING_DIR}"
              ]
            ],
            doGenerateSubmoduleConfigurations: false,
            submoduleCfg: [],
            userRemoteConfigs: [
              [
                url: "${env.GIT_REPO}"
              ]
            ]
          ]
        )

        dir("${env.WORKING_DIR}/data") {
          sh "tar cfvz jenkins.tar.gz *"
          sh "chmod 755 jenkins.tar.gz"
          sh "cp jenkins.tar.gz /home/ansible/.jenkins"
        }
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
